export const manageRolls = {
    GET_ROLLS_LIST_ACTION:"GET_ROLLS_LIST_ACTION",
    GET_ROLLS_LIST_SAGA:"GET_ROLLS_LIST_SAGA",
    DELETE_ROLL_ACTION:"DELETE_ROLL_ACTION",
    ADD_ROLL_ACTION:"ADD_ROLL_ACTION",
    UPDATE_SELECTED_ROW_ACTION:"UPDATE_SELECTED_ROW_ACTION",
    UPDATE_SELECTED_ROW_SAGA:"UPDATE_SELECTED_ROW_SAGA",
    GET_ROLE_PERMISSION_BY_ID_ACTION:"GET_ROLE_PERMISSION_BY_ID_ACTION",
    CHANGE_ROLE_PERMISSION_ACTION:"CHANGE_ROLE_PERMISSION_ACTION",
    CHANGE_ROLE_PERMISSION_SAGA:"CHANGE_ROLE_PERMISSION_SAGA",
    SAVE_ROLE_PERMISSION_SAGA:"SAVE_ROLE_PERMISSION_SAGA",
    APPLY_FILTERS_SAGA:"APPLY_FILTERS_SAGA",
}  