export const manageUsers = {
    GET_USER_LIST:"GET_USER_LIST",
    GET_ADMIN_USER_LIST:"GET_ADMIN_USER_LIST",
    GET_USER_LIST_ACTION:"GET_USER_LIST_ACTION",
    GET_ADMIN_USER_LIST_ACTION:"GET_ADMIN_USER_LIST_ACTION",
    DELETE_USER_ACTION:"DELETE_USER_ACTION",
    ADD_USER_ACTION:"ADD_USER_ACTION",
}  