export const managePermissions = {
    GET_ALL_PERMISSIONS_LIST_ACTION:"GET_ROLLS_LIST_ACTION",
    GET_ALL_PERMISSIONS_LIST_SAGA:"GET_ALL_PERMISSIONS_LIST_SAGA",
    ADD_NEW_PERMISSION_SAGA:"ADD_NEW_PERMISSION_SAGA",
    DELETE_PERMISSION_SAGA:"DELETE_PERMISSION_SAGA"
}